初期化の設計
PalmNeko/minishell pull request #31
Opened 2024-11-20 23:18 UTC by nytsdayo

設計できましたが、自信がないのと、リスト構造体の作り方がこんがらがりました。
一日中休むためひとまずプロトタイプの状態です。レビューお願いします。

2024-11-22 08:27 UTC, PalmNeko requested changes
* 抜けている宣言に関するコメント
* シェル変数に関するコメント
* サブシェルに関するコメント
* 誤字脱字？へのコメント
を行いました。

仕様を修正する必要性（日本語のmanと英語のmanが言ってることが違う）に気づいた為、一旦そちらの作業に移ります。

2024-11-22 08:27 UTC, PalmNeko commented on docs/design_ms_setup.md
> +struct struct s_malloc(){
`typedef struct s_malloc {` ではないでしょうか？
もしもそうであれば、修正願います。

2024-11-22 08:27 UTC, PalmNeko commented on docs/design_ms_setup.md
> +MNSH_SUBSHELL: サブシェルのネストレベル
シェル変数ですが、以下の変数は、仕様に含まれない変数です。
追加しますか？どうしますか？含める場合は、仕様の方を変更したのちに設計に反映お願いしいます。
 * IFS
 * MNSH
 * MNSHPID
 * SHLVL

謎の空行が入っているため、削除願います。意味がある場合は、コメントなどをお願いします。

2024-11-22 08:27 UTC, PalmNeko commented on docs/design_ms_setup.md
> +| MNSH_SUBSHELL | `0` |
上記のシェル変数のうち、仕様外の設計も行っているようなので、削除 or 仕様の変更願います。
仕様外のシェル変数は、仕様もしくは、シェル変数のセクションに書いたコメントを参照ください。

2024-11-22 08:27 UTC, PalmNeko commented on docs/design_ms_setup.md
> +| TMPDIR | `/tmp` |　<- 要確認お願いします
* HISTFILESIZE は、HISTSIZEの値を設定するようです。minishellを起動するときに、事前に環境変数として渡すことが可能なため、「HISTSIZEの値を設定する」等に変更すると良いでしょう。
* HISTSIZEは、デフォルト値で500を設定するようです。
 > 日本語のmanを見るとそのように書いてありますが、英語のmanを読むとまた違う書き方をしてあります。
 > 仕様の方の日本語のドキュメントに変更します。

 * TMPDIRはシェル変数として存在していますが、デフォルト設定はないようです。
ただし、mktemp関数などのTMPDIRを参照する関数はデフォルトで/tmpディレクトリを参照するようです。

2024-11-22 08:27 UTC, PalmNeko commented on docs/design_ms_setup.md
> +調査中m(_ _)m
サブシェルは初期化する必要ないかも？

2024-11-26 03:29 UTC, PalmNeko commented on docs/design_ms_setup.md
> +調査中m(_ _)m
> サブシェルで組み込みコマンドを呼んだ時にmishshellプログラムの実行環境ごと渡さないといけない？

この件に関しては、fork関数がそのまま使えるはずです。
コード内に記載しましたが、fork関数はプロセス情報以外のものを大体継承するはずです！
FDや変数etc...

ただし、日本語のmanの「コマンド実行環境」を見ると、シグナル系は再設定しているようです！（trapの部分）
```c

int a = 12; // 今まで行った処理。

t_pid pid = fork();
if (pid == 0)
{
    // fork関数までのすべてのメモリの内容を継承している。(同じメモリを参照しているわけではない。)
    // minishellであれば、シェル変数や環境変数、変更したFDなどが継承されている。
    // 継承されないものも一部あるが、記憶だと、プロセス情報由来のものだったはず。
    printf("%d\n", a); // 変数aが読み取れる。
    exit (0);
}
int status;
wait(&status); // この待ち方は多分よろしくない。
exit(0);
```

> その状況をインタプリタ状態と分けるべきなのかな？

インタラクティブとインタプリタで分ける必要は、、、多分･･･ない？
この話題は、日本語のmanで言うところの「コマンド実行環境」に当たると思いますが、ここには特にインタラクティブとインタプリタによって何かを変更するような記載はないように思います。
ので、多分、、、必要ない・・・。

> bminorのshell.cのmainの冒頭の方でそれっぽい処理が書いてあります

fork関数の性質上、冒頭には戻ることはないと思うので、大丈夫だと思います！

2024-11-26 03:50 UTC, PalmNeko commented on docs/design_ms_setup.md
> +調査中m(_ _)m
一部、間違えていました！
まだ調査が甘いですが、シグナル系もforkで継承されるようです！

2024-12-02 21:47 UTC, nytsdayo commented
初期化についての設計を書き直したのでレビューお願いします。

大変時間がかかって申し訳ないです。
不調及びbashの構造理解に時間がかかってしまいました。

- TTYであるかどうかの記述、追記しました。

下記、申し送り事項になります。
- 粒度：1130の対面MTGで話した方針（内部まではあまり書きすぎない）
- 3.ヒストリーの初期化と1.初期化の記述が矛盾している箇所(HISTSIZE)があるのでその整合性を取る必要がある
- 調査中の箇所
	- TTY判定について（今のままだと個人的に不明瞭なので明確にしたい）
	- 構造体のリストについて（要再学習）
	- サブシェルについて（基本初期化するものはないものだと思っているが、まだ不明瞭） 
- 要調査箇所
	- メモリの管理をする構造体について
	
予定としては、今日の夜・5日未明に2時間ほど修正、明日1時間ほど調査の計3時間でひとまず完成(?)の形に持っていきたいと考えています。

2024-12-02 23:35 UTC, nytsdayo commented
追加の申し送り事項
・環境変数 -> カーネル周り、何もわかってないことがわかったのでそこから調査することになりそうですm(_ _)m

2024-12-03 07:43 UTC, PalmNeko requested changes
全体的に読みやすかったです！
例があったり、set_handleのようにインデントで階層がわかりやすくようにしていたり読みやすいです！
説明も端的で良いと思います！
戻値も気をつけているようで良いと思います！

まだ、少し整合性の取れない部分があるようなのでその点に対してコメントしました！
（かなり仏頂面なコメントではありますが…。）

あと、少し手を加えれば問題なくなりそうなので引き続きよろしくおねがいします！

なるべく変更がプッシュされればレビューするようにしますね！
忘れることもあると思いますので、何かしらのコメントがあると嬉しいです！

後ちょいです！一緒に頑張りましょう〜(=^・^=)

2024-12-03 07:43 UTC, PalmNeko commented on docs/design_ms_setup.md
> +  }t_minishell
ms_malloc_listが型名は記載されていますが変数名がないです。
変数名を追加するか、削除するかお願いします。

2024-12-03 07:43 UTC, PalmNeko commented on docs/design_ms_setup.md
> +		int attr;
attrに使用する値はこちらで自由に決めて問題ないのでしょうか？
 > 問題ないとは思っていますが、一応確認のため。

2024-12-03 07:43 UTC, PalmNeko commented on docs/design_ms_setup.md
> +	} t_ms_malloc
`()`が不要です。削除願います。

リストは、次のリストを保存する変数は、t_listの方で対応可能なので削除願います。

2024-12-03 07:43 UTC, PalmNeko commented on docs/design_ms_setup.md
> +- 各変数について、下記処理を行ったあとシェル変数用の構造体変数に格納し、それを返す。
現在の書き方だと、下記処理を書いていないのか、`ms_initialize_env`がその処理を指しているのかが不明瞭です。
わかりやすく修正願います。

また、私がよりわかりやすいと感じる書き方の例としては、以下のとおりです。
* 「以降の兄弟セクションの処理を行ったあと」と記載する。
* `ms_initialize_env`の深さを`#####`とする。
* `*`を使って、次のようにする。
```md
- 各変数について、下記処理を行ったあとシェル変数用の構造体変数に格納し、それを返す。
    * ms_initialize_env
```

2024-12-03 07:43 UTC, PalmNeko commented on docs/design_ms_setup.md
> +| MNSH_SUBSHELL | `0` |
新しく属性が追加されたと思いますので、属性の情報も記載願います。

2024-12-03 07:43 UTC, PalmNeko commented on docs/design_ms_setup.md
> +| HISTSIZE | `0` |
`HISTSIZE`と`HISTFILESIZE`の値は上記の`ms_initialize_env`と同じ値ではないでしょうか。
そちらに合わせてください。

2024-12-03 07:43 UTC, PalmNeko commented on docs/design_ms_setup.md
ms_setupの戻り値と、引数がないっぽい？
追加お願いします！

2024-12-03 07:51 UTC, PalmNeko commented
わからない部分はコーディング中にわかる場合もあります！
最低限必要なのは、戻値と引数と説明なのでそこだけ気をつけてもらえたらと思います！

レビュー時にツッコまれたらその時考えましょう〜！
レビュー通った後に学習不足を感じるなら、TLPIを読みましょう〜！
「いくら調べても、いくら聞いてもわからない！」ということはしょっちゅうあります！
ですが、とりあえず先に進むと、その進んだ先に理解するヒントが落ちていたりもします！
わからないなら、とりあえず進むのじゃああ〜（コピペは厳禁）

2024-12-07 12:57 UTC, nytsdayo commented on docs/design_ms_setup.md
> +		int attr;
大丈夫です。よろしくおねがいします。

2024-12-07 13:04 UTC, nytsdayo commented on docs/design_ms_setup.md
> +- 各変数について、下記処理を行ったあとシェル変数用の構造体変数に格納し、それを返す。
順番が逆になっていました。m(__)m

2024-12-07 13:35 UTC, nytsdayo commented on docs/design_ms_setup.md
> +		int attr;
すみません、大きく仕様変えたいので再確認お願いします。

2024-12-07 14:02 UTC, nytsdayo commented on docs/design_ms_setup.md
> +- 各変数について、下記処理を行ったあとシェル変数用の構造体変数に格納し、それを返す。
envとｓhell_varを構造体で分けるのではなく属性で分けるようにしました。
確認よろしくおねがいします。

2024-12-07 14:10 UTC, nytsdayo commented on docs/design_ms_setup.md
> +| MNSH_SUBSHELL | `0` |
こちら、追加いたしましたのでご確認お願い致します。

2024-12-07 14:12 UTC, nytsdayo commented
大変おまたせしました...

①【報告】レビューでご指摘いただいたところの訂正を行いました。

②【報告】minishellの状態を管理する変数をひとまとめにしました。

③【質問】動的に確保した変数を管理する構造体変数のイメージが上手く出来ません。何か参考に出来るキーワードや資料などはありますでしょうか。

よろしくお願いします。

2024-12-12 07:10 UTC, merged